name 'ApacheSql_Integration'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ApacheSql_Integration'
long_description 'Installs/Configures ApacheSql_Integration'
version '0.2.0'
