name 'ApacheSql_Integration-0.1.0'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ApacheSql_Integration'
long_description 'Installs/Configures ApacheSql_Integration'
version '0.1.0'
chef_version '>= 14.0'
