name 'pizza'
maintainer 'kishore'
maintainer_email 'senaganassharikishore@cognizant.com'
license 'all_rights'
description 'Installs/Configures pizza'
long_description 'Installs/Configures pizza'
version '0.1.0'
